version: '3.8'

services:
  video_converter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3020"
    environment:
      - NODE_ENV=production
      - PORT=3020
    volumes:
      - .:/usr/src/app
    restart: unless-stopped